### PR TITLE
Add sidetab theme

### PR DESCRIPTION
**Pull request by CadaverLab**
Here's a screenshot https://i.imgur.com/GCWQOBM.png

### CODE REVIEW

**Comment by carnager** [comment]
thanks!

**Comment by BramVer** [comment]
I know this has already been merged and all,
but the bottom tabs aren't working for me when I use this theme (Execute/Activate/Window).
None of the modi are shown and there's no indication of which modus I'm using,
all the rest works perfectly fine.

Is this just a global rofi setting I'm missing, or is it something custom that wasn't pushed with the theme?
I'm on rofi 1.5.0-dirty.

**Comment by DaveDavenport** [comment]
you need to have sidebar-mode enabled.

**Comment by CadaverLab** [comment]
My bad. i'll update it.

**Pull request merged**
